[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "bibstyle"
version = "1.0.1"
description = "Personal BibTeX style checker"
authors = [{name="AJ Westley", email="alexanderjwestley@gmail.com"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = ['bibtexparser']

[project.urls]
Homepage = "https://github.com/AJWestley/BibStyle"

[project.scripts]
bibstyle = "bibstyle.cli:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
bibstyle = ["data/default_config.json"]